### ISSUE TITLE
为什么我的训练不收敛？

### ISSUE THREAD

**Issue by white2018** [shaoniangu/FashionAI_Keypoint_Detection_Using_CPM#1]
@shaoniangu 你好

我参考了你的代码，用keras重写了cpm，但是训练时候不收敛。不知道什么原因？能给点提示吗？谢谢

我用的是coco2017的骨骼关键点来训练cpm的。数据预处理时候，首先扣出人体的bbox，然后以padding方式resize到368*368。
计算loss时候，尝试了每阶段heatmap的所有点的loss值和只有关键点附近的loss值两种方式，都不收敛。

如果能帮忙的话，我将关键代码发到你的信箱shaoniangu@163.com。谢谢

下图是data generator生成的input_image和heatmap
![Uploading image.png…]()

**Comment by shaoniangu** [comment]
可以，发给我看看吧。




| |
Youzhi Gu
邮箱：shaoniangu@163.com
|

Signature is customized by Netease Mail Master

在2018年10月10日 19:43，white 写道：

@shaoniangu 你好

我参考了你的代码，用keras重写了cpm，但是训练时候不收敛。不知道什么原因？能给点提示吗？谢谢

我用的是coco2017的骨骼关键点来训练cpm的。数据预处理时候，首先扣出人体的bbox，然后以padding方式resize到368*368。
计算loss时候，尝试了每阶段heatmap的所有点的loss值和只有关键点附近的loss值两种方式，都不收敛。

如果能帮忙的话，我将关键代码发到你的信箱shaoniangu@163.com。谢谢

下图是data generator生成的input_image和heatmap

**Comment by shaoniangu** [comment]
同学你好，
很高兴和你交流。
你每阶段计算loss是指的是每一个stage都计算一次loss然后反传优化吗？
你先给我看看loss的代码吧。希望能够帮到你。

古有志




| |
Youzhi Gu
邮箱：shaoniangu@163.com
|

Signature is customized by Netease Mail Master

在2018年10月11日 00:05，Youzhi Gu 写道：
可以，发给我看看吧。




| |
Youzhi Gu
邮箱：shaoniangu@163.com
|

Signature is customized by Netease Mail Master

在2018年10月10日 19:43，white 写道：

@shaoniangu 你好

我参考了你的代码，用keras重写了cpm，但是训练时候不收敛。不知道什么原因？能给点提示吗？谢谢

我用的是coco2017的骨骼关键点来训练cpm的。数据预处理时候，首先扣出人体的bbox，然后以padding方式resize到368*368。
计算loss时候，尝试了每阶段heatmap的所有点的loss值和只有关键点附近的loss值两种方式，都不收敛。

如果能帮忙的话，我将关键代码发到你的信箱shaoniangu@163.com。谢谢

下图是data generator生成的input_image和heatmap

**Comment by white2018** [comment]
> 同学你好， 很高兴和你交流。 你每阶段计算loss是指的是每一个stage都计算一次loss然后反传优化吗？ 你先给我看看loss的代码吧。希望能够帮到你。 古有志 | | Youzhi Gu 邮箱：shaoniangu@163.com | Signature is customized by Netease Mail Master 在2018年10月11日 00:05，Youzhi Gu 写道： 可以，发给我看看吧。 | | Youzhi Gu 邮箱：shaoniangu@163.com | Signature is customized by Netease Mail Master 在2018年10月10日 19:43，white 写道： @shaoniangu 你好 我参考了你的代码，用keras重写了cpm，但是训练时候不收敛。不知道什么原因？能给点提示吗？谢谢 我用的是coco2017的骨骼关键点来训练cpm的。数据预处理时候，首先扣出人体的bbox，然后以padding方式resize到368*368。 计算loss时候，尝试了每阶段heatmap的所有点的loss值和只有关键点附近的loss值两种方式，都不收敛。 如果能帮忙的话，我将关键代码发到你的信箱shaoniangu@163.com。谢谢 下图是data generator生成的input_image和heatmap — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

每阶段计算loss是指的是每一个stage都计算一次loss然后反传优化吗？
---应该是的

代码已经发到你的邮箱了。loss的定义如下：
total_loss = 0.5 * K.sum(K.square((y_pred - y_true) *
                                 K.cast(y_true > 1e-5, K.floatx()))) / self.batch_size
其中，K.cast(y_true > 1e-5, K.floatx())的用途是只取关节点附近的点进行loss计算。
